#19 Shift Logger
Inbibo/shift_docs pull request #38
Opened 2024-08-22 08:49 UTC by juliavisserinbibo

## Issue
Closes #19 

## Description 
This PR addresses the content of the Shift Logger page. This page provides a more detailed explanation of the logger and how it can be configured through environment variables. This includes:

- Log levels available and colors
- How to set the debug level in the UI
- Where to find Shift logs
- How to configure the logger through environment variables

2024-08-22 11:33 UTC, hectorjimenezinbibo requested changes

2024-08-22 11:33 UTC, hectorjimenezinbibo commented on docs/reference/logger.md
> +|`SHIFT_LOG_LEVEL`| The default log level when starting Shift| "*WARNING*"
```suggestion
|`SHIFT_LOG_LEVEL`| The default log level when starting Shift.| "*WARNING*"

```

2024-08-22 14:44 UTC, hectorjimenezinbibo approved these changes

2024-08-23 08:00 UTC, albertochimentiinbibo requested changes

2024-08-23 08:00 UTC, albertochimentiinbibo commented on docs/reference/logger.md
> +|`SHIFT_LOG_DIRECTORY`| The location of log files.| "*C:/Users/[USERNAME]/AppData/Local/Temp/Shift*"
```suggestion
|`SHIFT_LOG_DIRECTORY`| The location of log files.| "*C:/Users/[USERNAME]/AppData/Local/Temp/Shift*" (only in Windows)

```

2024-08-23 14:11 UTC, JorgeHernandezibanezinbibo approved these changes

2024-08-26 07:07 UTC, juliavisserinbibo commented on docs/reference/logger.md
> +All messages caught by the Logger are recorded in log files. Shift uses a rotating file handler, meaning that new logs will be created when the file exceeds a specific size without exceeding a set nu
I forgot this is specific to windows... we should add Linux too?

2024-08-27 11:20 UTC, juliavisserinbibo commented on docs/reference/logger.md
> +All messages caught by the Logger are recorded in log files. Shift uses a rotating file handler, meaning that new logs will be created when the file exceeds a specific size without exceeding a set nu
I added a box with the example
![image](https://github.com/user-attachments/assets/fe6af0b8-4268-453a-9f40-1f64b29049e1)

2024-08-27 11:20 UTC, juliavisserinbibo commented on docs/reference/logger.md
> +|`SHIFT_LOG_DIRECTORY`| The location of log files.| "*C:/Users/[USERNAME]/AppData/Local/Temp/Shift*"
I changed to a description

2024-08-28 09:29 UTC, leegeertseninbibo approved these changes

2024-09-02 10:21 UTC, albertochimentiinbibo approved these changes

2024-09-02 10:42 UTC, merged