#33 Shift Introduction
Inbibo/shift_docs pull request #53
Opened 2024-08-29 10:07 UTC by juliavisserinbibo

## Issue
Closes #33

## Descritpion
This issue addresses the content of Shift's introduction page. This page should provide a short description of what Shift is, key features and why Shift is ideal for the user. It should also provide some links to the first steps for getting shift started.

### Note
I based this page on https://inbibo.co.uk/docs/adonisfx/v1.2.0/introduction introduction page and the content from the Shift product page. 
Please, if you want to add anything or reword a section let me know.

2024-08-30 09:06 UTC, JorgeHernandezibanezinbibo approved these changes

2024-08-30 14:00 UTC, leegeertseninbibo requested changes

2024-08-30 14:00 UTC, leegeertseninbibo commented on docs/index.md
> +With Shift you can use libraries of operators and workflows, connect them together and intuitively build complex processes. Being based on Python, means that Shift gives you the freedom to implement
```suggestion
With Shift you can use libraries of operators, connect them together and intuitively build workflows to run complex processes. Being based on Python, means that Shift gives you the freedom to implement any type of workflow.
```

2024-08-30 14:19 UTC, juliavisserinbibo commented on docs/index.md
> +Welcome to the technical documentation of Shift where we provide you with all the information you need to use the software in your digital characters. If you need more information or help, please do
Done

2024-09-02 09:52 UTC, leegeertseninbibo approved these changes

2024-09-02 10:59 UTC, albertochimentiinbibo requested changes

2024-09-03 08:48 UTC, hectorjimenezinbibo approved these changes

2024-09-03 10:10 UTC, juliavisserinbibo commented on docs/index.md
> +- **Easy to Use**: Most automation in VFX, Animation and Video Games relies on the availability of people with software development skills. Shift node-based approach is more familiar to many digital
Done

2024-09-03 10:10 UTC, juliavisserinbibo commented on docs/index.md
> +- **Lean & Scalable**: Working with many interconnected pipeline scripts makes it difficult to follow the pace enforced by production. Using operator catalogs and working with processes as assets (no
Done

2024-09-03 10:10 UTC, juliavisserinbibo commented on docs/index.md
> +- have a common technology foundation for your team.
Done

2024-09-04 10:24 UTC, albertochimentiinbibo approved these changes

2024-09-04 10:27 UTC, merged